version: 2
jobs:
  build:
    working_directory: /go/src/github.com/juanaveragedeveloper/circleci_tutorial
    docker:
      - image: circleci/golang:1.12
    environment:
      GOBIN: /go/bin/
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: go env
      - run: go install hello.go
      - run: hello
